address: ":8080"
metrics_address: ":9090"
grcp_address: ":8080"

# this is set because the service is behind an ssl ingress
insecure_server: true
autocert: false

policy:
  # from and to should be set to the prometheus ingress
  - from: https://prometheus.example.com
    to: https://prometheus.example.com
    allowed_idp_claims:
      groups:
        # ldap groups configured in dex
        - group1
        - group2
